stages:
  - test

ui_smoke:
  image: mcr.microsoft.com/playwright:v1.54.1-noble
  stage: test
  script:
    - cd playwright-suite
    - npm ci
    - npx playwright test --grep @smoke
  artifacts:
    when: always
    paths:
      - playwright-suite/playwright-report/
